[package]
name = "tauri-app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.93.0"

[lib]
name = "tauri_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", default-features = false, features = [] }

[dependencies]
tauri = { version = "2.11.5", features = [] }
tauri-plugin-wallpaper = { path = "../../" }
